services:
  ginlab:
    build:
      context: .
      target: dev
      dockerfile: docker/go.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app  # Монтируем код
    environment:
      - TZ=Europe/Moscow
      - AIR_ENV=DEV
      - GOCACHE=/app/.cache
    command: air